### ISSUE TITLE
CKAN to frictionless: `path` is overridden if both `path` and `url` set in CKAN resource

### ISSUE THREAD

**Issue by shevron** [frictionlessdata/frictionless-ckan-mapper#37]
# Overview

If a CKAN data package resource has both `path` and `url` set, `path` will be overwritten. It is not clear what the expected behavior here, but it is possible that for `path` as well as for other keys, we should not be touching them if they exist, just unset the conflicting key, or maybe even through an exception if both keys are set so that using code can handle gracefully. 

We should either:
1. Change this so that existing keys are never overwritten, or
2. Decide that existing keys are *always* overwritten, or
3. Throw an exception if a target key already exists before conversion

In any case we should document the correct behavior.

---

Please preserve this line to notify @amercader (lead of this repository)

**Comment by shevron** [comment]
Note: this is also true for all other directly mapped attributes:
```python
resource_mapping = {
    'size': 'bytes',
    'mimetype': 'mediatype',
    'url': 'path'
}
```

**Comment by rufuspollock** [comment]
@shevron the defined behaviour is this atm:

* We preserve extras in c2f conversion
* We convert 3 specific keys: url => path, mimetype, size
  * + license and contributors (but in a smart way e.g. preserving the extras info we have and only overriding explicitly)

My suggest you in use in CKAN is you have a special value for path:

* Run ckan 2 frictionless
* Then set the path

**Comment by rufuspollock** [comment]
WONTFIX / FIXED.

**Comment by shevron** [comment]
@rufuspollock that's fine but to clarify, it means we are *changing* our original requirement in https://github.com/datopian/ckanext-versioning/issues/2 which was that if both `path` and `url` are set in a CKAN resource we just use `path` as is. I'm fine with that, just clarifying.

**Comment by rufuspollock** [comment]
@shevron i don't see that as changing it here - since **path does not exist** in the original CKAN resource afaict ... (does it?)

**Comment by shevron** [comment]
Ok, sure - that part is clear. In our original definition of the `ckanext-versioning` path generation algorithm we discussed a case in which both `url` and `path` exist as keys in the original CKAN resource. If I understand correctly, it makes more sense to ignore that case and just let `path` be overwritten by `ckan_to_frictionless` and then mangle it in any way needed in `ckanext-versioning`. 

That sounds like the right approach to me.

**Comment by rufuspollock** [comment]
@shevron my point would be that *if* `path` did exist then ckanext-versioning would be what would take care of making sure that passed through (i.e. ckan_to_frictionless.dataset would use url and then ckanext-versioning could override with original path value).

**Comment by shevron** [comment]
@rufuspollock Ok, now I got it. Thanks for clarifying.
