### ISSUE TITLE
Some items kept in `extras` after frictionless => CKAN conversion cause CKAN to fail with ValidationError

### ISSUE THREAD

**Issue by shevron** [frictionlessdata/frictionless-ckan-mapper#39]
# Overview

When a package is converted from CKAN to frictionless and back again🦶, some items are saved in `extras` such as `id` and `contributors`. Some of the `extras` may be read and used to set values when converting from frictionless to CKAN, but they are not popped out of the `extras` list and are kept there. 

This can then cause issues when trying to pass the resulting CKAN package dict through CKAN's own validation (e.g. when calling `package_update()` on the same package), because CKAN will throw an error:

```
ValidationError: {u'extras': [{}, {}, {'key': [u'There is a schema field with the same name']}]}
```

This happens because `extras` now contains keys that are already defined in the CKAN dataset schema such as `id`. 

For `ckanext-versioning`, we worked around this by filtering out values from extras that already exist as properties of the package dict, but others may be hitting this as well. See our workaround in https://github.com/datopian/ckanext-versioning/pull/19/files#diff-3a58033cd97812191417c36622c5aa7bR123

---
Please preserve this line to notify @amercader (lead of this repository)

**Comment by rufuspollock** [comment]
`contributors` is intentional as it is tough to know if there was not some extra stuff in there that does not map across. `id` is a bug and will get fixed.
