### ISSUE TITLE
[f2c] Expected behavior when mapping `contributors` and `licenses`

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionless-ckan-mapper#42]
When converting from _Frictionless to CKAN_, we expect `contributors` and `licenses` to disappear from `extras` **if** there is already an author/maintainer or license at the "root" (outside `extras`). However, this leads to corner cases. The following is what I understand the correct behavior to be — please point out if I'm mistaken about something.

---

#### ONE maintainer and/or ONE author (+ emails)
* Keep everything at the root, remove from `extras` ⇒ remove duplicate information.

#### >= 2 authors and/or >= 2 maintainer (+ emails)
* Keep the first one of each type and remove **everything** from `extras` ⇒ information lost.
* @pdelboca's use case: there's always only one author and/or maintainer coming from Frictionless.

#### In both preceding cases...
* Is it possible that CKAN will be storing one author/maintainer already that's different from the one(s) listed in `extras`? If so, do we just discard the keys in `extras`?

---

#### ONE license
* Discard from `extras` if already at the root ⇒ remove duplicate information.
* If **not** at the root but in `extras` only, keep at the root and remove from `extras`.
  

#### >= 2 licenses
* Discard in `extras` **only** the one already listed in CKAN or **everything**?
* @pdelboca's use case: there's always only one license in the Frictionless `licenses` list.
* If we don't have a license in CKAN but we have multiple licenses in `licenses` ⇒ keep the first one?

#### In both preceding cases...
* As with authors/maintainers, can we have different licenses in `extras` that do not match what's at the root?

---

## Acceptance / Task

* [ ] Be clear on how to deal with extra information coming from `licenses` and `contributors`.

---

## Analysis

Proposed algorithm for `contributors`:

* if `contributors` has length 1 or 2 and number of authors and maintainer types <= 1 THEN delete

⇒ What if there are more contributors? Delete?
⇒ What if we don't have author/maintainer info at the root? (Will that ever happen or do we necessarily start with a valid CKAN package that's then converted to a Frictionless package?)

/cc @rufuspollock @pdelboca

**Comment by rufuspollock** [comment]
@sglavoie can you write out a simple example of input and expected output and that can then be reviewed. We should not lose information.

**Comment by sglavoie** [comment]
@rufuspollock, the following is a simple output from the different scenarios described above.

**Input 1 — Single author, single license:**

```
{
 'author': u'Patricio Del Boca',
 'author_email': u'',
 'extras': [{'key': u'contributors',
             'value': '[{"role": "author", "email": "", "title": "Patricio Del Boca"}]'},
            {'key': u'licenses',
             'value': '[{"path": "http://www.opendefinition.org/licenses/cc-by", "name": "cc-by", "title": "Creative Commons Attribution"}]'}],
 'license_id': u'cc-by',
 'license_title': u'Creative Commons Attribution',
 'license_url': u'http://www.opendefinition.org/licenses/cc-by'
 }
```


**Output 1:**

```
{
  u'author': u'Patricio Del Boca',
  u'author_email': u'',
  u'extras': [],
  u'license_id': u'cc-by',
  u'license_title': u'Creative Commons Attribution',
  u'license_url': u'http://www.opendefinition.org/licenses/cc-by'
 }
```

**Input 2 — multiple contributors:**

```
{
 'author': u'Patricio Del Boca',
 'author_email': u'',
 'extras': [
     {'key': u'contributors',
         'value': '[
             {"role": "author", "email": "", "title": "Patricio Del Boca"},
             {"role": "maintainer", "email": "", "title": "Rufus"},
             {"role": "author", "email": "", "title": "Sebastien"},
             {"role": "maintainer", "email": "", "title": "Paul"},
         ]'}
  ]
 }
```

**Output 2 — keep everything in `extras`:**

```
{
 'author': u'Patricio Del Boca',
 'author_email': u'',
 'maintainer': u'Rufus',
 'maintainer_email': u'',
 'extras': [
     {'key': u'contributors',
         'value': '[
             {"role": "author", "email": "", "title": "Patricio Del Boca"},
             {"role": "maintainer", "email": "", "title": "Rufus"},
             {"role": "author", "email": "", "title": "Sebastien"},
             {"role": "maintainer", "email": "", "title": "Paul"},
         ]'}
  ]
 }
```

**Input 3 — multiple licenses:**

```
{
 'author': u'Patricio Del Boca',
 'author_email': u'',
 'extras': [{'key': u'contributors',
             'value': '[{"role": "author", "email": "", "title": "Patricio Del Boca"}]'},
            {'key': u'licenses',
             'value': '[
             {"path": "http://www.opendefinition.org/licenses/cc-by", "name": "cc-by", "title": "Creative Commons Attribution"},
             {"path": "http://www.example.org/licenses/cc-by2", "name": "cc-by2", "title": "Creative Commons Attribution 2"}]'}
            ],
 'license_id': u'cc-by',
 'license_title': u'Creative Commons Attribution',
 'license_url': u'http://www.opendefinition.org/licenses/cc-by'
 }
```

**Output 3 — keep everything from `licenses` in `extras`, don't keep `author` in `extras` (point brought by @pdelboca):**

```
{
 'author': u'Patricio Del Boca',
 'author_email': u'',
 'extras': [{'key': u'licenses',
             'value': '[
             {"path": "http://www.opendefinition.org/licenses/cc-by", "name": "cc-by", "title": "Creative Commons Attribution"},
            {"path": "http://www.example.org/licenses/cc-by2", "name": "cc-by2", "title": "Creative Commons Attribution 2"}
            ]'}],
 'license_id': u'cc-by',
 'license_title': u'Creative Commons Attribution',
 'license_url': u'http://www.opendefinition.org/licenses/cc-by'
 }
```

**Comment by rufuspollock** [comment]
FIXED. See the related commits above.
