### ISSUE TITLE
Publish new version on PyPI

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/frictionless-ckan-mapper#51]
@frictionlessdata/datopian Can you give me and @aivuk admin rights on the `frictionless-ckan-mapper` PyPI project so we can publish new versions?

 https://pypi.org/project/frictionless-ckan-mapper/

Many thanks!

**Comment by anuveyatsu** [comment]
@amercader I've shared access to the project with you - could you check now if you can manage the collaborators in PyPI?

**Comment by amercader** [comment]
I have access now, thanks @anuveyatsu!
